create table ref_achievement
(
    id            int                  not null
        primary key,
    type_id       int                  null,
    name          tinytext             null,
    description   tinytext             null,
    icon_url      tinytext             null,
    is_increasing tinyint(1) default 1 not null,
    constraint ref_achievement_ref_achievement_type_id_fk
        foreign key (type_id) references ref_achievement_type (id)
);

INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (1, 1, 'Master of Titles', 'Earn chess titles', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (2, 1, 'Pawn Exterminator', 'Capture all opponent\'s pawns', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (3, 1, 'Chess Strategist', 'Deliver a check', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (4, 1, 'Promotion Master', 'Promote a large number of pieces', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (5, 1, 'Distinction Collector', 'Earn each of the Awards', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (6, 1, 'Mating Knight', 'Checkmate with a knight', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (7, 1, 'Vertical Executioner', 'Checkmate with a pawn', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (8, 1, 'Number One', 'Reach #1 in the rankings', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (9, 1, 'Checkless Victor', 'Win without being checked', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (10, 1, 'Brave Against Odds', 'Lose a game after 50 moves', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (11, 2, 'Match Veteran', 'Play a large number of games (counted at the end of the month)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (12, 2, 'Unyielding', 'Play a large number of lost games (counted at the end of the month)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (13, 2, 'Draw Strategist', 'Play a large number of drawn games (counted at the end of the month)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (14, 2, 'Classical Player', 'Play a large number of classical games (counted at the end of the month)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (15, 2, 'Top 100 Rival', 'Play a large number of games against the top 100 ranked players (monthly count)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (16, 2, 'Black Warrior', 'Play a large number of games as Black (monthly count)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (17, 2, 'League Player', 'Play a large number of league games (monthly count)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (18, 2, 'Challenger', 'Play a large number of Challenge tournament games (monthly count)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (19, 2, 'Championship Contender', 'Play a large number of World Championship games (monthly count)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (20, 2, 'MASTERS Player', 'Play a large number of MASTERS tournament games (monthly count)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (21, 3, 'Victor', 'Achieve a high number of wins', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (22, 3, 'Winning Streak', 'Achieve a long winning streak', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (23, 3, 'Triumph with Black', 'Win many games as Black', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (24, 3, 'Tournament Champion', 'Win many games in a single tournament', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (25, 3, 'Grandmaster Slayer', 'Defeat grandmasters', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (26, 3, 'Chess Triumph', 'Win by check', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (27, 3, 'Classic Master', 'Win many classical games', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (28, 3, 'Flawless Victor', 'Win without losing a piece', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (29, 3, 'Castling-Free Winner', 'Win without castling', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (30, 3, 'Queenless Winner', 'Win without using the queen', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (31, 4, 'Medal Master', 'Earn many medals', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (32, 4, 'Trophy Collector', 'Earn unique trophies', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (33, 4, 'Gold Medalist', 'Earn many gold medals', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (34, 4, 'Medal Defender', 'Defend earned medals', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (35, 4, 'K.O. Victor', 'Win knockout tournaments', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (36, 4, 'League Victor', 'Win leagues', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (37, 4, 'Challenger', 'Win Challenge tournaments', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (38, 4, 'Swiss Champion', 'Win Swiss tournaments', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (39, 4, 'Cup Winner', 'Win Cup tournaments', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (40, 4, 'MASTERS Champion', 'Win MASTERS tournaments', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (41, 5, 'Master MVP', 'Best player in the season ranking', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (42, 5, 'Master Consequencer', 'Most consecutive wins', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (43, 5, 'Master Total Winner', 'Most total wins', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (44, 5, 'Master Trophier', 'Most medals earned (based on medal count and medal value: 3-gold, 2-silver, 1-bronze, then ranked)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (45, 5, 'Master Ratiolation', 'Best win/loss ratio', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (46, 5, 'Master Battler', 'Most games player', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (47, 5, 'Master Unbeatable', 'Hardest to beat (fewest losses in a season)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (48, 5, 'Master Hardbreaker', 'Most wins playing as Black', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (49, 5, 'Master Checkmasters', 'Most checkmates', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (50, 5, 'Master Swisterlands', 'Most wins in Swiss games', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (51, 6, 'Seasoned Veteran', 'Complete many seasons', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (52, 6, 'Medal Player', 'Earn many medals in a single season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (53, 6, 'Seasonal Standout', 'Receive many awards in a single season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (54, 6, 'Active Player', 'Play many games in a single season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (55, 6, 'Seasonal Victor', 'Win many games in a single season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (56, 6, 'Monthly Leader', 'Be MVP of the month in a season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (57, 6, 'Loss Record Holder', 'Lose the fewest games in a season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (58, 6, 'Draw Record Holder', 'Draw the fewest games in a season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (59, 6, 'Grandmaster Challenge', 'Play many games against grandmasters in a single season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (60, 6, 'Swiss Victor', 'Win many Swiss tournaments in a single season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (61, 7, 'Move Maker', 'Make many moves', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (62, 7, 'Castler', 'Perform many castlings', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (63, 7, 'Speedy Pawn', 'Make many double-step pawn moves', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (64, 7, 'Mobile King', 'Move the king many times', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (65, 7, 'Black Operator', 'Make many moves as Black', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (66, 7, 'White Operator', 'Make many moves as White', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (67, 7, 'Queen Strategist', 'Move the queen many times', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (68, 7, 'Agile Knight', 'Move the knight many times', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (69, 7, 'Precise Bishop', 'Move the bishop many times', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (70, 7, 'Mobile Rooktower', 'Move the rook many times', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (71, 8, 'Piece Master', 'Capture opponent\'s pieces', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (72, 8, 'White Hunter', 'Capture opponent\'s white pieces', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (73, 8, 'Black Hunter', 'Capture opponent\'s black pieces', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (74, 8, 'Queen Destroyer', 'Capture opponent\'s queens', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (75, 8, 'Strong Piece Hunter', 'Capture opponent\'s strong pieces (queen, rook, bishop, knight)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (76, 8, 'Pawn Executioner', 'Capture opponent\'s pawns', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (77, 8, 'Knight Hunter', 'Capture opponent\'s knights', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (78, 8, 'Bishop Hunter', 'Capture opponent\'s bishops', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (79, 8, 'Rook Hunter', 'Capture opponent\'s rooks', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (80, 8, 'En Passant Master', 'Capture pawns en passant', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (81, 9, 'Ranking Master', 'Highest ranking position', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (82, 9, 'Ranking Conqueror', 'Total rating points gained', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (83, 9, 'Higher Rated Slayer', 'Wins against higher-rated players (monthly count)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (84, 9, 'Monthly Ranker', 'Months without a rating drop', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (85, 9, 'Ranking Rise', 'Gain ranking positions (only upward movement counts)', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (86, 9, 'Seasonal Ruler', 'Points earned in a single season', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (87, 9, 'Monthly Topper', 'Points earned in a single month', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (88, 9, 'Steady in Top 100', 'Top 100 in ranking for consecutive months', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (89, 9, 'Minimal Scorer', 'At least 100 rating points in consecutive months', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (90, 9, 'MVPoints Gatherer', 'More rating points earned than the second-best player', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (91, 10, 'Blitz Master', 'Blitz games played', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (92, 10, 'Black Conqueror', 'Blitz wins as Black', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (93, 10, 'Clock Tactician', 'Blitz wins with more time left than opponent', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (94, 10, 'Superspeed Winner', 'Win in under 1 minute', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (95, 10, 'King of Rapid', 'Win in under 10 minutes', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (96, 10, 'Opening Master', 'Win in under 20 moves', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (97, 10, 'Chess Marathoner', 'Games with at least 40 moves', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (98, 10, 'Lightning Chess', 'Deliver check in under 5 moves', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (99, 10, 'Late Castling', 'Castle only after move 10', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
INSERT INTO test_chess.ref_achievement (id, type_id, name, description, icon_url, is_increasing) VALUES (100, 10, 'Unbeaten in Opening', 'Don’t lose a piece in the first 10 moves', 'http://milkyway.local/chess/res/icon/achievement/box.png', 1);
