create table ref_player_cpu_subgroup
(
    id       int         not null
        primary key,
    name     varchar(50) null,
    group_id int         null,
    constraint ref_player_cpu_subgroup_ref_player_group_id_fk
        foreign key (group_id) references ref_player_cpu_group (id)
);

INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (1, 'AI Enthusiasts', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (2, 'Gadget Lovers', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (3, 'Coders', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (4, 'Cybersecurity Buffs', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (5, 'Blockchain Believers', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (6, 'Robotics Fans', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (7, 'Data Scientists', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (8, 'Tech Reviewers', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (9, 'App Developers', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (10, 'Smart Home Users', 1);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (11, 'Writers', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (12, 'Designers', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (13, 'Painters', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (14, 'Musicians', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (15, 'Photographers', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (16, 'Filmmakers', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (17, 'Poets', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (18, 'Illustrators', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (19, 'Dancers', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (20, 'Crafters', 2);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (21, 'Runners', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (22, 'Cyclists', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (23, 'Swimmers', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (24, 'Gym Goers', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (25, 'Hikers', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (26, 'Yogis', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (27, 'Martial Artists', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (28, 'Crossfitters', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (29, 'Skaters', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (30, 'Climbers', 3);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (31, 'Historians', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (32, 'Art Critics', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (33, 'Theater Fans', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (34, 'Museum Visitors', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (35, 'Classical Music Lovers', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (36, 'Bookworms', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (37, 'Language Learners', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (38, 'Folklore Followers', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (39, 'Philosophers', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (40, 'Anthropology Enthusiasts', 4);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (41, 'Movie Buffs', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (42, 'Series Bingers', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (43, 'Music Fans', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (44, 'Meme Lords', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (45, 'Stand-Up Lovers', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (46, 'Anime Watchers', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (47, 'Stream Followers', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (48, 'Reality TV Fans', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (49, 'Comedy Lovers', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (50, 'Pop Culture Analysts', 5);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (51, 'PC Gamers', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (52, 'Console Players', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (53, 'Mobile Gamers', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (54, 'Retro Gamers', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (55, 'eSports Fans', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (56, 'RPG Lovers', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (57, 'Strategy Players', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (58, 'FPS Gamers', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (59, 'Casual Gamers', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (60, 'Streamer Fans', 6);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (61, 'Quiz Takers', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (62, 'Fact Collectors', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (63, 'Documentary Watchers', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (64, 'Science Explorers', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (65, 'Puzzle Solvers', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (66, 'Book Readers', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (67, 'Podcast Listeners', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (68, 'Amateur Researchers', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (69, 'Trivia Fans', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (70, 'Knowledge Sharers', 7);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (71, 'Partygoers', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (72, 'Event Organizers', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (73, 'Community Builders', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (74, 'Influencers', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (75, 'Chatty Ones', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (76, 'Meetup Hosts', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (77, 'Club Members', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (78, 'Social Media Fans', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (79, 'Volunteers', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (80, 'Networkers', 8);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (81, 'Meditators', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (82, 'Minimalists', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (83, 'Philosophical Thinkers', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (84, 'Journal Keepers', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (85, 'Mindfulness Practitioners', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (86, 'Spiritual Seekers', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (87, 'Deep Listeners', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (88, 'Self-Improvers', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (89, 'Emotional Explorers', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (90, 'Life Coaches', 9);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (91, 'Trend Followers', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (92, 'Startup Fans', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (93, 'Eco-Conscious', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (94, 'Remote Workers', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (95, 'Urban Nomads', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (96, 'Digital Natives', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (97, 'Fashionistas', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (98, 'Crypto Users', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (99, 'Smart Consumers', 10);
INSERT INTO test_chess.ref_player_cpu_subgroup (id, name, group_id) VALUES (100, 'Tech-Integrated', 10);
