create table temp_tournament_phases
(
    id                     int                  not null
        primary key,
    tournament_id          int                  not null,
    phase_id               int                  not null,
    name                   varchar(50)          not null,
    description            varchar(255)         null,
    groups_count           int                  null,
    group_size             int                  null,
    type_id                int                  null,
    promotion_position     int                  null,
    degradation_position   int                  null,
    points_multiplier      double               null,
    starting_month         int        default 1 null comment '1 - for Jan, 12 - for Dec',
    updated_at_month_start tinyint(1) default 0 null comment 'flag if may be updated at START_MONTH process',
    constraint temp_tournament_phases_pk
        unique (tournament_id, phase_id),
    constraint temp_tournament_phases_ref_tournament_id_fk
        foreign key (tournament_id) references ref_tournament (id),
    constraint temp_tournament_phases_ref_tournament_phase_type_id_fk
        foreign key (type_id) references ref_tournament_phase_type (id)
);

INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (1, 1, 1, 'Master Division', 'League, Master division', 1, 24, 1, 0, 17, 1.5, 1, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (2, 2, 1, 'First Round', 'Derby, First Round', 128, 2, 2, 1, 2, 1, 10, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (3, 3, 1, 'Group Phase', 'World Cup, Group Phase', 8, 8, 1, 4, 5, 1.5, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (4, 4, 1, 'Group Phase', 'Continental Cup - Africa, Group Phase', 8, 4, 1, 2, 3, 1.2, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (5, 5, 1, 'Phase 1', 'Swiss National, Phase 1', 20, 50, 1, 5, 6, 1, 1, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (6, 6, 1, 'Phase 1', 'Swiss Continental, Phase 1', 7, 50, 1, 10, 11, 1.1, 3, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (7, 7, 1, 'Phase 1', 'Swiss World, Phase 1', 1, 70, 1, 3, 4, 1.2, 7, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (8, 8, 1, 'Phase 1', 'Swiss Random, Phase 1', 10, 100, 1, 3, 4, 1.1, 5, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (9, 9, 1, 'Group Phase 1', 'Cup of Nations, Group Phase 1', 16, 4, 1, 3, 4, 1.2, 8, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (10, 10, 1, 'Round 1', 'Winning Challenge, K.O. Round 1', 256, 2, 2, 1, 2, 1, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (12, 12, 1, 'Masters', 'Masters Phase', 1, 13, 1, 1, 4, 2, 12, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (13, 1, 2, '1st Division', 'League, 1st Division', 2, 20, 1, 4, 13, 1.4, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (14, 2, 2, 'Second Round', 'Derby, Second Round', 64, 2, 2, 1, 2, 1.1, 10, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (15, 3, 2, 'First K.O. Phase', 'World Cup, First K.O. Phase', 16, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (16, 4, 2, 'Group Phase', 'Continental Cup - America North, Group Phase', 8, 4, 1, 2, 3, 1.2, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (17, 5, 2, 'Phase 2', 'Swiss National, Phase 2', 20, 50, 1, 5, 6, 1, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (18, 6, 2, 'Phase 2', 'Swiss Continental, Phase 2', 7, 50, 1, 10, 11, 1.1, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (19, 7, 2, 'Phase 2', 'Swiss World, Phase 2', 1, 70, 1, 3, 4, 1.2, 10, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (20, 8, 2, 'Phase 2', 'Swiss Random, Phase 2', 20, 50, 1, 3, 4, 1.1, 9, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (21, 9, 2, 'Group Phase 2', 'Cup of Nations, Group Phase 2', 8, 6, 1, 4, 5, 1.4, 8, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (22, 10, 2, 'Round 2', 'Winning Challenge, K.O. Round 2', 128, 2, 2, 1, 2, 1.1, 2, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (23, 11, 2, 'Round 1', 'Fourth Challenge, Round 1', 64, 4, 1, 1, 3, 1.4, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (24, 1, 3, '2nd Division', 'League, 2nd Division', 4, 18, 1, 4, 11, 1.3, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (25, 2, 3, 'Third Round', 'Derby, Third Round', 32, 2, 2, 1, 2, 1.2, 10, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (26, 3, 3, 'Second K.O. Phase', 'World Cup, Second K.O. Phase', 8, 2, 2, 1, 2, 2.5, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (27, 4, 3, 'Group Phase', 'Continental Cup - America South, Group Phase', 8, 4, 1, 2, 3, 1.2, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (28, 5, 3, 'Phase 3', 'Swiss National, Phase 3', 20, 50, 1, 3, 4, 1, 4, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (29, 6, 3, 'Phase 3', 'Swiss Continental, Phase 3', 7, 20, 1, 5, 6, 1.1, 8, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (30, 7, 3, 'Phase 3', 'Swiss World, Phase 3', 1, 35, 1, 3, 4, 1.2, 12, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (31, 8, 3, 'Phase 3', 'Swiss Random, Phase 3', 50, 20, 1, 3, 4, 1.1, 11, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (32, 9, 3, 'Group Phase 3', 'Cup of Nations, Group Phase 3', 4, 8, 1, 6, 7, 1.6, 8, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (33, 10, 3, 'Round 3', 'Winning Challenge, K.O. Round 3', 64, 2, 2, 1, 2, 1.2, 3, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (34, 11, 3, 'Round 2', 'Fourth Challenge, Round 2', 16, 4, 1, 1, 3, 1.6, 3, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (35, 1, 4, '3rd Division', 'League, 3rd Division', 8, 16, 1, 4, 9, 1.2, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (36, 2, 4, 'Fourth Round', 'Derby, Fourth Round', 16, 2, 2, 1, 2, 1.3, 10, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (37, 3, 4, 'Quater Finals', 'World Cup, Quater Finals', 4, 2, 2, 1, 2, 3, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (38, 4, 4, 'Group Phase', 'Continental Cup - Antartica, Group Phase', 8, 4, 1, 2, 3, 1.2, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (39, 9, 4, 'Group Phase 4', 'Cup of Nations, Group Phase 4', 2, 12, 1, 8, 9, 1.8, 8, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (40, 10, 4, 'Round 4', 'Winning Challenge, K.O. Round 4', 32, 2, 2, 1, 2, 1.3, 3, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (41, 11, 4, 'Round 3', 'Fourth Challenge, Round 3', 4, 4, 1, 1, 3, 1.8, 4, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (42, 1, 5, '4th Division', 'League, 4th Division', 16, 16, 1, 4, 9, 1.1, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (43, 2, 5, 'Fifth Round', 'Derby, Fifth Round', 8, 2, 2, 1, 2, 1.4, 11, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (44, 3, 5, 'Semi Finals', 'World Cup, Semi Finals', 2, 2, 2, 1, 2, 4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (45, 4, 5, 'Group Phase', 'Continental Cup - Asia, Group Phase', 8, 4, 1, 2, 3, 1.2, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (46, 9, 5, 'Group Phase 5', 'Cup of Nations, Group Phase 5', 1, 16, 1, 1, 16, 2, 8, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (47, 10, 5, 'Round 5', 'Winning Challenge, K.O. Round 5', 16, 2, 2, 1, 2, 1.4, 4, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (48, 11, 5, 'Final', 'Fourth Challenge, Final', 1, 4, 1, 1, 4, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (49, 1, 6, '5th Division', 'League, 5th Division', 32, 15, 1, 4, 99, 1, 2, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (50, 2, 6, 'Quarter Final', 'Derby Quater Final', 4, 2, 2, 1, 2, 1.5, 11, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (51, 3, 6, 'Finals', 'World Cup, Finals', 2, 2, 2, 1, 2, 5, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (52, 4, 6, 'Group Phase', 'Continental Cup - Australia, Group Phase', 8, 4, 1, 2, 3, 1.2, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (53, 10, 6, 'Round 6', 'Winning Challenge, K.O. Round 6', 8, 2, 2, 1, 2, 1.5, 4, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (54, 2, 7, 'Semi Final', 'Derby Semi Final', 2, 2, 2, 1, 2, 1.8, 11, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (55, 4, 7, 'Group Phase', 'Continental Cup - Europe, Group Phase', 8, 4, 1, 2, 3, 1.2, 6, 1);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (56, 10, 7, 'Quater Finals', 'Winning Challenge, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (57, 2, 8, 'Final', 'Derby Final', 1, 2, 2, 1, 2, 2, 11, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (58, 10, 8, 'Semi Finals', 'Winning Challenge, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (59, 10, 9, 'Final', 'Winning Challenge, Final', 1, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (61, 4, 11, 'First K.O. Phase', 'Continental Cup - Africa, First K.O. Phase', 8, 2, 2, 1, 2, 1.4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (62, 4, 12, 'First K.O. Phase', 'Continental Cup - America North, First K.O. Phase', 8, 2, 2, 1, 2, 1.4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (63, 4, 13, 'First K.O. Phase', 'Continental Cup - America South, First K.O. Phase', 8, 2, 2, 1, 2, 1.4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (64, 4, 14, 'First K.O. Phase', 'Continental Cup - Antartica, First K.O. Phase', 8, 2, 2, 1, 2, 1.4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (65, 4, 15, 'First K.O. Phase', 'Continental Cup - Asia, First K.O. Phase', 8, 2, 2, 1, 2, 1.4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (66, 4, 16, 'First K.O. Phase', 'Continental Cup - Australia, First K.O. Phase', 8, 2, 2, 1, 2, 1.4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (67, 4, 17, 'First K.O. Phase', 'Continental Cup - Europe, First K.O. Phase', 8, 2, 2, 1, 2, 1.4, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (68, 4, 21, 'Quarter Finals', 'Continental Cup - Africa, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (69, 4, 22, 'Quarter Finals', 'Continental Cup - America North, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (70, 4, 23, 'Quarter Finals', 'Continental Cup - America South, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (71, 4, 24, 'Quarter Finals', 'Continental Cup - Antartica, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (72, 4, 25, 'Quarter Finals', 'Continental Cup - Asia, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (73, 4, 26, 'Quarter Finals', 'Continental Cup - Australia, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (74, 4, 27, 'Quarter Finals', 'Continental Cup - Europe, Quater Finals', 4, 2, 2, 1, 2, 1.6, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (75, 4, 31, 'Semi Finals', 'Continental Cup - Africa, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (76, 4, 32, 'Semi Finals', 'Continental Cup - America North, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (77, 4, 33, 'Semi Finals', 'Continental Cup - America South, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (78, 4, 34, 'Semi Finals', 'Continental Cup - Antartica, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (79, 4, 35, 'Semi Finals', 'Continental Cup - Asia, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (80, 4, 36, 'Semi Finals', 'Continental Cup - Australia, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (81, 4, 37, 'Semi Finals', 'Continental Cup - Europe, Semi Finals', 2, 2, 2, 1, 2, 1.8, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (82, 4, 41, 'Finals', 'Continental Cup - Africa, Finals', 2, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (83, 4, 42, 'Finals', 'Continental Cup - America North, Finals', 2, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (84, 4, 43, 'Finals', 'Continental Cup - America South, Finals', 2, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (85, 4, 44, 'Finals', 'Continental Cup - Antartica, Finals', 2, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (86, 4, 45, 'Finals', 'Continental Cup - Asia, Finals', 2, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (87, 4, 46, 'Finals', 'Continental Cup - Australia, Finals', 2, 2, 2, 1, 2, 2, 6, 0);
INSERT INTO test_chess.temp_tournament_phases (id, tournament_id, phase_id, name, description, groups_count, group_size, type_id, promotion_position, degradation_position, points_multiplier, starting_month, updated_at_month_start) VALUES (88, 4, 47, 'Finals', 'Continental Cup - Europe, Finals', 2, 2, 2, 1, 2, 2, 6, 0);
